FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migration
WORKDIR /src

# Copy only the project files first for caching restore
COPY Server/Api/Api.csproj ./Server/Api/
WORKDIR /src/Server/Api
RUN dotnet restore

# Copy the rest of the code
COPY Server/Api/ ./
RUN dotnet build -c Release

# Install EF CLI
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# Set working dir for EF commands
WORKDIR /src/Server/Api
ENTRYPOINT ["dotnet-ef"]
