apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-movieapp-to-db
  namespace: db
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: movieapp
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-movieapp-to-cache
  namespace: cache
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: movieapp
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-movieapp-to-storage
  namespace: storage
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: movieapp
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9001
