name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push Backend
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${REPO_OWNER}/movie-backend:${{ github.sha }} ./Server/Api
          docker push ghcr.io/${REPO_OWNER}/movie-backend:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push Frontend
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${REPO_OWNER}/movie-frontend:${{ github.sha }} ./Web/client
          docker push ghcr.io/${REPO_OWNER}/movie-frontend:${{ github.sha }}

  build-migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push migration
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -f ./Server/Api/Dockerfile_migrations -t ghcr.io/${REPO_OWNER}/movie-backend-migrations:${{ github.sha }} ./Server/Api/
          docker push ghcr.io/${REPO_OWNER}/movie-backend-migrations:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend, build-migration]
    steps:
      - uses: actions/checkout@v3

      - name: Package Helm chart
        run: |
          helm package ./Helm/movieapp --destination ./artifacts
          ls -lh ./artifacts

      - name: Connect GitHub runner to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Copy Helm chart package to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.K3S_SERVER }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          source: "artifacts/*.tgz"
          target: "/home/${{ secrets.K3S_USER }}/"

      - name: Apply Database Migrations
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.K3S_SERVER }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          script: |
            export GITHUB_SHA=${{ github.sha }}
            export CONNECTION_STRING="Host=postgres-postgresql.db.svc.cluster.local;Port=5432;Database=movies;Username=postgres;Password=${{ secrets.DB_PASSWORD }}"
            
            # Create a temporary manifest file on the remote server
            # The 'tee' command writes the manifest to a file
            cat <<EOF | tee /tmp/migration-job.yaml > /dev/null
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: backend-db-migration-${GITHUB_SHA}
              namespace: movieapp
            spec:
              template:
                spec:
                  containers:
                  - name: migration-container
                    image: "ghcr.io/ahmadelhanafy/movie-backend-migrations:${GITHUB_SHA}"
                    command: ["dotnet", "ef", "database", "update", "--no-build"]
                    env:
                    - name: ConnectionStrings__DefaultConnection
                      value: "${CONNECTION_STRING}"
                  restartPolicy: OnFailure
            EOF
            
            # Apply the manifest
            kubectl apply -f /tmp/migration-job.yaml
            
            # Use a loop to check the job status until it's complete
            for i in $(seq 1 12); do
              # Check if the job is complete, successful, or has failed
              if kubectl get job backend-db-migration-${GITHUB_SHA} -n movieapp -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep "True"; then
                echo "Job completed successfully."
                kubectl logs job/backend-db-migration-${GITHUB_SHA} -n movieapp
                break
              fi
              
              if kubectl get job backend-db-migration-${GITHUB_SHA} -n movieapp -o jsonpath='{.status.failed}' | grep -E "[1-9]"; then
                echo "Job failed."
                kubectl logs job/backend-db-migration-${GITHUB_SHA} -n movieapp
                exit 1
              fi
              
              echo "Waiting for job to complete..."
              sleep 20
            done
            
            # Clean up the job after the loop
            kubectl logs job/backend-db-migration-${GITHUB_SHA} -n movieapp
            kubectl delete -f /tmp/migration-job.yaml

      - name: Deploy to k3s via Helm
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.K3S_SERVER }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          script: |
            export GITHUB_SHA=${{ github.sha }}

            CHART=$(ls ~/artifacts/movieapp-0.1.0.tgz | sort | tail -n1)

            helm upgrade --install movieapp $CHART \
              --namespace movieapp \
              --create-namespace \
              --set backend.image.tag=${GITHUB_SHA} \
              --set frontend.image.tag=${GITHUB_SHA}
