name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t ghcr.io/<your-username>/movie-backend:${{ github.sha }} ./Api
          docker push ghcr.io/<your-username>/movie-backend:${{ github.sha }}

      - name: Build & Push Frontend
        run: |
          docker build -t ghcr.io/<your-username>/movie-frontend:${{ github.sha }} ./Web
          docker push ghcr.io/<your-username>/movie-frontend:${{ github.sha }}
    
