name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Backend
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${REPO_OWNER}/movie-backend:${{ github.sha }} ./Server/Api
          docker push ghcr.io/${REPO_OWNER}/movie-backend:${{ github.sha }}
      
      - name: Build & Push Frontend
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${REPO_OWNER}/movie-frontend:${{ github.sha }} ./Web/client
          docker push ghcr.io/${REPO_OWNER}/movie-frontend:${{ github.sha }}

      - name: Connect GitHub runner to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          
      - name: Deploy to k3s via Helm
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.K3S_SERVER }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          script: |
            helm upgrade --install movieapp ./Helm/movieapp \
            --namespace movieapp \
            --create-namespace \
            --set backend.image.tag=${GITHUB_SHA} \
            --set frontend.image.tag=${GITHUB_SHA}

